source $HOME/.vim/init/plug.vimrc               " plugin loader
source $HOME/.vim/init/themes.vimrc             " themes settings
source $HOME/.vim/init/general.vimrc            " general settings
source $HOME/.vim/init/keys.vimrc               " leader key settings
source $HOME/.vim/init/snippets.vimrc           " snippets settings
source $HOME/.vim/init/languageSwitch.vimrc     " language settings
